spring:
  application:
    name: 'stay-a-programmer'

  datasource:
    url: 'jdbc:postgresql://localhost:5432/shop_db'
    username: root
    password: LetMeIn
    driver-class: org.postgresql.Driver

  redis:
    host: localhost
    port: 6397
    password: LetMeIn

server:
  servlet:
    context-path: '/api'

config:
  cookie:
    max-age: 86400
