spring:
  application:
    name: 'stay-a-programmer'

  datasource:
    url: 'jdbc:postgresql://localhost:5432/shop_db'
    username: root
    password: LetMeIn

    hikari:
      connection-timeout: 10000

  redis:
    host: localhost
    port: 6397
    password: LetMeIn
